---
- name: Restart OpenAFS servers
  become: yes
  service:
    name: "{{ ansible_local.openafs.server_service_name }}"
    state: restarted
  when:
    - ansible_local.openafs.server_service_name is defined
    - afs_server_service_results.changed is defined
    - not afs_server_service_result.changed
