---
- name: Restart OpenAFS servers
  become: yes
  service:
    name: "{{ afs_server_service_name }}"
    state: restarted
  when:
    - afs_server_service_results is defined
    - not afs_server_service_result.changed
