---
dependency:
  name: galaxy
platforms:
  - name: m-role-krbserver${AFS_TESTID}
    box: "${AFS_IMAGE:-generic/centos7}"
    groups:
      - afs_kdcs
provisioner:
  name: ansible
  env:
    ANSIBLE_PIPELINING: "True"
    ANSIBLE_STDOUT_CALLBACK: "yaml"
  inventory:
    group_vars:
      all:
        afs_realm: "${AFS_REALM:-EXAMPLE.COM}"
        afs_realm_files: "${MOLECULE_EPHEMERAL_DIRECTORY}"
verifier:
  name: ansible
scenario:
  create_sequence:
    - create
    - prepare
  check_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - prepare
    - converge
  destroy_sequence:
    - cleanup
    - destroy
  test_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
