---
- name: "Install run levels."
  become: yes
  file:
    state: link
    src: /etc/init.d/openafs-server
    path: "{{ rc }}"
  loop:
    - /etc/rc0.d/K99openafs-server
    - /etc/rc2.d/S99openafs-server
  loop_control:
    loop_var: rc

- name: "Run init script."
  become: yes
  command:
    cmd: /etc/init.d/openafs-server start
  changed_when: true
