namespace: openafs_contrib
name: openafs
version: 1.5.0-rc2
readme: README.md
authors:
  - Cheyenne Wills <cwills@sinenomine.net>
  - Marc 'risson' Schmitt <marc.schmitt@risson.space>
  - Mark Vitale <mvitale@sinenomine.net>
  - Michael Meffie <mmeffie@sinenomine.net>
  - Ralf Brunckhorst <rbrunckhorst@sinenomine.net>
description: Playbooks, roles, and modules to deploy the OpenAFS distributed filesystem.
license: BSD-2-Clause
tags:
  - openafs
build_ignore:
  - '.gitignore'
  - '.venv'
  - 'builds'
  - 'docs'
  - 'tests'
  - 'Makefile'
  - 'requirements.txt'
  - '*/.cache'
  - '*/Makefile'
  - '*/molecule'
  - '*/.pytest*'
  - '*/pytest.*'
repository: 'https://github.com/openafs-contrib/ansible-openafs'
