namespace: openafs_contrib
name: openafs
version: 1.3.0
readme: README.md
authors:
  - Michael Meffie <mmeffie@sinenomine.net>
  - Cheyenne Wills <cwills@sinenomine.net>
description: Playbooks, roles, and modules to deploy the OpenAFS distributed filesystem.
license: BSD-2-Clause
tags:
  - openafs
build_ignore:
  - '.gitignore'
  - '.venv'
  - 'builds'
  - 'docs'
  - 'tests'
  - 'Makefile'
  - 'requirements.txt'
  - '*/.cache'
  - '*/Makefile'
  - '*/molecule'
  - '*/.pytest*'
  - '*/pytest.*'
dependencies:
  ansible.posix: '>=1.2.0'
repository: 'https://github.com/openafs-contrib/ansible-openafs'
