namespace: openafs_contrib
name: openafs
version: 1.1.0
readme: README.md
authors:
  - Michael Meffie <mmeffie@sinenomine.net>
  - Cheyenne Wills <cwills@sinenomine.net>
  - Mark Vitale <mvitale@sinenomine.net>
description: Playbooks, roles, and modules to deploy the OpenAFS distributed filesystem.
license: BSD-2-Clause
tags:
  - openafs
build_ignore:
  - .gitignore
  - .venv
  - builds
  - tools
  - roles/*/.env.yml
  - roles/*/.tests
  - roles/*/.cache
dependencies:
  ansible.posix: '>=1.2.0'
repository: 'https://github.com/openafs-contrib/ansible-openafs'
