---
- name: Restart OpenAFS client
  become: yes
  service:
    name: "{{ ansible_local.openafs.client_service_name }}"
    state: restarted
  when:
    - ansible_local.openafs.client_service_name is defined
    - afs_client_service_result.changed is defined
    - not afs_client_service_result.changed
