---
- name: Restart OpenAFS client
  become: yes
  service:
    name: "{{ afs_client_service_name }}"
    state: restarted
  when:
    - _afs_use_client_service_mgr | d('yes') | bool
    - not afs_client_service_result.changed
