---
# Default configure options for Solaris.
_afs_configure_options:
  enable:
    - transarc-paths
    - debug
    - debug-kernel
    - kernel-module
  disable:
    - optimize

# Default nolibafs configure options for Solaris.
_afs_nolibafs_configure_options:
  enable:
    - transarc-paths
    - debug
  disable:
    - kernel-module
    - optimize
