---
- name: Build binary distribution
  hosts: all
  tasks:
    - import_role:
        name: openafs_devel

    - name: Checkout source
      git:
        repo: "{{ afs_git_repo }}"
        version: "{{ afs_git_version }}"
        dest: "~/openafs"

    - name: Get version string
      command:
        cmd: build-tools/git-version .
        chdir: "~/openafs"
      changed_when: false
      register: git_version

    - name: Build
      openafs_contrib.openafs.openafs_build:
        target: dest
        clean: yes
        projectdir: "~/openafs"
        destdir: "~/openafs/packages/dest"
        configure_options:
          enable:
            - debug
            - debug-kernel
            - kernel-module
            - transarc-paths
          with:
            - linux-kernel-packaging
      register: build_results

    - set_fact:
        osdist: "{{ ansible_distribution | lower + ansible_distribution_major_version }}"
        arch: "{{ ansible_architecture }}"
        version: "{{ git_version.stdout | replace('-', '_') }}"

    - set_fact:
        tarball: "openafs-{{ version }}-{{ osdist }}-{{ arch }}.bdist.tar.gz"

    - name: Create archive
      archive:
        path: "~/openafs/packages/dest/"
        dest: "{{ tarball }}"
        format: gz

    - name: Download
      fetch:
        flat: yes
        src: "{{ tarball }}"
        dest: "~/.cache/ansible-openafs/builds/"
      register: fetch_results

    - name: Downloaded
      debug:
        var: fetch_results.dest
