---
- name: Build binary distribution
  hosts: all
  tasks:
    - import_role:
        name: openafs_devel

    - name: Checkout source
      git:
        repo: "{{ afs_git_repo }}"
        version: "{{ afs_git_version }}"
        dest: "~/openafs"

    - name: Build
      openafs_contrib.openafs.openafs_build:
        clean: yes
        projectdir: "~/openafs"
        destdir: "~/openafs/packages/dest"
        build_userspace: yes
        build_module: yes
        with_transarc_paths: yes
      register: build_results

    - debug:
        var: build_results

    - set_fact:
        osdist: "{{ ansible_distribution | lower + ansible_distribution_major_version }}"
        arch: "{{ ansible_architecture }}"
        version: "{{ build_results.version | replace('-', '_') }}"

    - set_fact:
        tarball: "openafs-{{ version }}-{{ osdist }}-{{ arch }}.bdist.tar.gz"

    - name: Create archive
      archive:
        path: "~/openafs/packages/dest/"
        dest: "{{ tarball }}"
        format: gz

    - name: Download
      fetch:
        flat: yes
        src: "{{ tarball }}"
        dest: "~/.cache/ansible-openafs/builds/"
      register: fetch_results

    - name: Downloaded
      debug:
        var: fetch_results.dest
