---
- name: Checkout info
  debug:
    msg: 'Checkout source code: {{ afs_git_repo }} with version {{ afs_git_version }} to {{ afs_topdir }}'

- name: Checkout source code
  git:
    repo: "{{ afs_git_repo }}"
    version: "{{ afs_git_version }}"
    dest: "{{ afs_topdir }}"
  register: checkout_results
