---
- name: Import common definitions
  import_role:
    name: openafs_contrib.openafs.openafs_common

- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ role_path }}/vars/{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_version }}.yaml"
    - "{{ role_path }}/vars/{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_major_version }}.yaml"
    - "{{ role_path }}/vars/{{ ansible_distribution | replace(' ', '_') }}.yaml"
    - "{{ role_path }}/vars/{{ ansible_os_family }}.yaml"
    - "{{ role_path }}/vars/{{ ansible_system }}.yaml"
    - "{{ role_path }}/vars/defaults.yaml"

- include_tasks: "system-{{ afs_firewall }}.yaml"
  when: afs_firewall is defined

- name: Install packages
  include_tasks: "{{ item }}"
  with_first_found:
    - "install-packages/{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_version }}.yaml"
    - "install-packages/{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_major_version }}.yaml"
    - "install-packages/{{ ansible_distribution | replace(' ', '_') }}.yaml"
    - "install-packages/{{ ansible_os_family }}.yaml"
    - "unknown.yaml"

- name: Store installation facts
  become: yes
  openafs_contrib.openafs.openafs_store_facts:
    state: update
    facts:
      bins:
        kdb5_util: "{{ afs_kdb5_util }}"
      krbserver:
        krb5_conf: "{{ afs_krbserver_krb5_conf }}"
        kdc_conf: "{{ afs_krbserver_kdc_conf }}"
        kadm5_acl: "{{ afs_krbserver_kadm5_acl }}"
        principal: "{{ afs_krbserver_principal | d(omit) }}"
        stash: "{{ afs_krbserver_stash | d(omit) }}"
        dict:  "{{ afs_krbserver_dict | d(omit) }}"
        kdc_service: "{{ afs_krbserver_kdc_service }}"
        admin_service: "{{ afs_krbserver_admin_service }}"
  when: not ansible_check_mode

- name: Set default realm
  become: yes
  template:
    src: krb5.conf.j2
    dest: "{{ afs_krbserver_krb5_conf }}"
    owner: root
    group: "{{ afs_root_group }}"
    mode: 0644

- name: Configure kerberos key server
  become: yes
  template:
    src: kdc.conf.j2
    dest: "{{ afs_krbserver_kdc_conf }}"
    owner: root
    group: "{{ afs_root_group }}"
    mode: 0600
  notify:
    - Restart kerberos key server

- name: Ensure acl file exists
  become: yes
  template:
    force: no
    src: kadm5.acl.j2
    dest: "{{ afs_krbserver_kadm5_acl }}"
    owner: root
    group: "{{ afs_root_group }}"
    mode: 0600

- name: Create kerberos kdc database
  become: yes
  command: >
    {{ afs_kdb5_util }}
    -P {{ afs_krb_master_password }}
    -r {{ afs_realm }}
    create -s
  args:
    creates: "{{ afs_krbserver_principal }}"
  register: krb5_util_results

- name: Create admin principal
  become: yes
  openafs_contrib.openafs.openafs_principal:
    state: present
    principal: "{{ afs_krb_admin_principal }}"
    acl: "*"
    kadmin: "{{ afs_kadmin_local | default(omit) }}"
  register: admin_principal_results

- name: Download admin keytab
  become: yes
  fetch:
    flat: yes
    src: "{{ admin_principal_results.keytab }}"
    dest: "{{ afs_realm_files }}/"
  when: not ansible_check_mode
  register: download_results

- name: Downloaded.
  debug:
    var: download_results.dest
  when: not ansible_check_mode

- name: Start kerberos key server
  become: yes
  service:
    name: "{{ afs_krbserver_kdc_service }}"
    enabled: yes
    state: started
  register: afs_krbserver_kdc_service_result

- name: Start kerberos admin server
  become: yes
  service:
    name: "{{ afs_krbserver_admin_service }}"
    enabled: yes
    state: started
  register: afs_krbserver_admin_service_result
