---
- name: Unsupported platform
  fail:
    msg: >
      Install method is '{{ afs_install_method }}'.
      Platform is
      '{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_version }}',
      '{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_major_version }}',
      '{{ ansible_distribution | replace(' ', '_') }}',
      '{{ ansible_os_family }}',
      '{{ ansible_system }}'.
