---
- name: Gather
  setup:
  when: ansible_distribution is undefined

- name: Install kernel headers
  include_tasks: "{{ afs_devel_kheaders_tasks }}"
  with_first_found:
    - "kheaders/{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_version }}.yaml"
    - "kheaders/{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_major_version }}.yaml"
    - "kheaders/{{ ansible_distribution | replace(' ', '_') }}.yaml"
    - "kheaders/{{ ansible_os_family | replace(' ', '_') }}.yaml"
    - "kheaders/{{ ansible_system | replace(' ', '_') }}.yaml"
    - "kheaders/unknown.yaml"
  loop_control:
    loop_var: afs_devel_kheaders_tasks
  when: afs_devel_kernel_headers | d('yes') | bool

- name: Install development tools and libraries
  include_tasks: "{{ afs_devel_install_tasks }}"
  with_first_found:
    - "install/{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_version }}.yaml"
    - "install/{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_major_version }}.yaml"
    - "install/{{ ansible_distribution | replace(' ', '_') }}.yaml"
    - "install/{{ ansible_os_family | replace(' ', '_') }}.yaml"
    - "install/{{ ansible_system | replace(' ', '_') }}.yaml"
    - "install/unknown.yaml"
  loop_control:
    loop_var: afs_devel_install_tasks
