---
- name: Create lock directory.
  become: yes
  file:
    state: directory
    path: /var/lock/subsys
    owner: root
    group: root
    mode: "0755"

- name: Install init script.
  become: yes
  template:
    src: "{{ _afs_server_init_script | d('openafs-server.init.j2') }}"
    dest: /etc/init.d/openafs-server
    owner: root
    group: root
    mode: "0744"
