---
- name: Create lock directory.
  become: yes
  file:
    state: directory
    path: /var/lock/subsys
    owner: root
    group: root
    mode: "0755"

- name: Install init script.
  become: yes
  template:
    src: "{{ _afs_server_init_script | d('openafs-server.init.j2') }}"
    dest: /etc/init.d/openafs-server
    owner: root
    group: root
    mode: "0744"

- name: Install run levels.
  become: yes
  file:
    state: link
    src: /etc/init.d/openafs-server
    path: "{{ rc }}"
  loop:
    - /etc/rc0.d/K99openafs-server
    - /etc/rc2.d/S99openafs-server
  loop_control:
    loop_var: rc
