---
- name: Checkout source
  git:
    repo: "{{ afs_git_repo }}"
    version: "{{ afs_git_version }}"
    dest: "~/openafs"

- name: Build source distribution
  command:
    cmd: perl build-tools/make-release --dir=packages HEAD
    chdir: "~/openafs"

- name: Build rpms
  openafs_build_redhat_rpms:
    build: all
    sdist: ~/openafs/packages
  register: build_results

- debug:
    var: build_results

- name: Create archive
  vars:
    version: "{{ build_results.version.openafs_version }}"
    dist: "{{ ansible_distribution | replace(' ', '_') | lower + ansible_distribution_major_version }}"
    arch: "{{ ansible_architecture }}"
  block:
    - name: Create archive
      archive:
        path: "{{ build_results.rpms }}"
        dest: "openafs-{{ version }}-{{ dist }}-{{ arch }}.rpms.tar.gz"
        format: gz
        force_archive: yes

    - name: Download
      fetch:
        flat: yes
        src: "openafs-{{ version }}-{{ dist }}-{{ arch }}.rpms.tar.gz"
        dest: "{{ afs_builds }}/"
      register: fetch_results

    - name: Downloaded
      debug:
        msg: "{{ fetch_results.dest }}"
