---
- name: Create lock directory.
  become: yes
  file:
    state: directory
    path: /var/lock/subsys
    owner: root
    group: root
    mode: "0755"

- name: Install init script.
  become: yes
  template:
    src: "{{ _afs_client_init_script }}"
    dest: /etc/init.d/openafs-client
    owner: root
    group: root
    mode: "0744"
