---
- name: Create a Kerberos realm
  hosts: afs_kdcs
  collections:
    - openafs_contrib.openafs
  tasks:
    - import_role:
        name: openafs_krbserver

    - import_role:
        name: openafs_common

    - name: Create AFS service key.
      become: yes
      openafs_principal:
        state: present
        principal: "afs/{{ afs_cell }}"
        encryption_types:
          - aes128-cts
          - aes256-cts
      register: service_key_results

    - name: Create admin principal.
      become: yes
      openafs_principal:
        state: present
        principal: "{{ afs_admin }}"
        acl: "*"
      register: admin_princ_results

    - name: Create user principal.
      become: yes
      openafs_principal:
        state: present
        principal: "test"
      register: user_princ_results

    - name: Download keytabs.
      become: yes
      fetch:
        flat: yes
        src: "{{ item }}"
        dest: "{{ afs_cell_files }}/"
      with_items:
        - "{{ service_key_results.keytab }}"
        - "{{ admin_princ_results.keytab }}"
        - "{{ user_princ_results.keytab }}"
      when: not ansible_check_mode
      register: download_results

    - name: Downloaded.
      debug:
        msg: "{{ download_results.results | map(attribute='dest') | list }}"
      when: not ansible_check_mode
